-- Chess tables used by nextjs-shared/src/chess/ functions.
-- These tables live in the consuming project's database.
-- This file is documentation only — it is not executed by the app.
--
-- This is the CANONICAL definition of tgr_gamesraw / tgd_gamesdecon.
-- The code that reads/writes these tables (sync.ts, deconstruct.ts) lives here,
-- so this file is the single source of truth for their shape. Consuming projects'
-- own scripts/schema.sql copies must be kept in sync with this file by hand.

CREATE TABLE tgr_gamesraw (
  gr_grid            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gr_player_username VARCHAR(64) NOT NULL,
  gr_chesscom_uuid   VARCHAR(64) NOT NULL,
  gr_raw_data        JSONB NOT NULL,
  gr_pgn             TEXT,
  gr_end_time        INTEGER NOT NULL,
  gr_time_class      VARCHAR(16),
  UNIQUE (gr_chesscom_uuid, gr_player_username)
);

CREATE TABLE tgd_gamesdecon (
  gd_gdid              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gd_grid              INTEGER NOT NULL,
  gd_chesscom_uuid     VARCHAR(64),
  gd_white_username    VARCHAR(64) NOT NULL,
  gd_black_username    VARCHAR(64) NOT NULL,
  gd_white_rating      INTEGER NOT NULL,
  gd_black_rating      INTEGER NOT NULL,
  gd_player_username   VARCHAR(64) NOT NULL,
  gd_player_color      VARCHAR(5) NOT NULL,
  gd_player_result     VARCHAR(8) NOT NULL,
  gd_opponent_username VARCHAR(64) NOT NULL,
  gd_opponent_rating   INTEGER NOT NULL,
  gd_time_class        VARCHAR(16) NOT NULL,
  gd_time_control      VARCHAR(32),
  gd_is_rated          BOOLEAN NOT NULL DEFAULT TRUE,
  gd_termination       VARCHAR(64),
  gd_end_time          INTEGER NOT NULL,
  gd_eco_code          VARCHAR(8),
  gd_opening_name      TEXT,
  gd_game_url          TEXT,
  gd_opening_moves     TEXT,
  gd_pgn               TEXT,
  UNIQUE (gd_grid)
);

CREATE INDEX idx_tgr_end_time ON tgr_gamesraw USING btree (gr_end_time DESC);
CREATE INDEX idx_tgr_has_pgn ON tgr_gamesraw USING btree (gr_grid) WHERE (gr_pgn IS NOT NULL);
CREATE INDEX idx_tgr_player ON tgr_gamesraw USING btree (gr_player_username);

CREATE INDEX idx_tgd_eco ON tgd_gamesdecon USING btree (gd_eco_code);
CREATE INDEX idx_tgd_end_time ON tgd_gamesdecon USING btree (gd_end_time DESC);
CREATE UNIQUE INDEX idx_tgd_grid ON tgd_gamesdecon USING btree (gd_grid);
CREATE INDEX idx_tgd_opponent ON tgd_gamesdecon USING btree (gd_opponent_username);
CREATE INDEX idx_tgd_player ON tgd_gamesdecon USING btree (gd_player_username);
CREATE INDEX idx_tgd_result ON tgd_gamesdecon USING btree (gd_player_result);
CREATE INDEX idx_tgd_time_class ON tgd_gamesdecon USING btree (gd_time_class);
