CREATE TABLE public.xlg_logging (
    lg_lgid integer NOT NULL,
    lg_severity character(1),
    lg_level integer NOT NULL DEFAULT 1,
    lg_isupdate boolean NOT NULL DEFAULT false,
    lg_caller character varying DEFAULT ''::character varying,
    lg_functionname character varying NOT NULL,
    lg_dbkey character varying,
    lg_table character varying DEFAULT ''::character varying,
    lg_msg character varying NOT NULL,
    lg_datetime timestamp with time zone NOT NULL,
    lg_sql_raw text,
    lg_sql_params jsonb,
    lg_sql_readable text
);

ALTER TABLE public.xlg_logging ALTER COLUMN lg_lgid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.xlg_logging_lg_lgid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.xlg_logging
    ADD CONSTRAINT xlg_logging_pkey PRIMARY KEY (lg_lgid);

CREATE TABLE public.xrtg_routing (
    rtg_rtgid integer NOT NULL,
    rtg_table character varying NOT NULL,
    rtg_dbkey character varying NOT NULL
);

ALTER TABLE public.xrtg_routing ALTER COLUMN rtg_rtgid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.xrtg_routing_rtg_rtgid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.xrtg_routing
    ADD CONSTRAINT xrtg_routing_pkey PRIMARY KEY (rtg_rtgid);

ALTER TABLE ONLY public.xrtg_routing
    ADD CONSTRAINT xrtg_routing_rtg_table_key UNIQUE (rtg_table);

CREATE TABLE public.ttst_test (
    tst_tstid integer NOT NULL,
    tst_note character varying
);

ALTER TABLE public.ttst_test ALTER COLUMN tst_tstid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ttst_test_tst_tstid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.ttst_test
    ADD CONSTRAINT ttst_test_pkey PRIMARY KEY (tst_tstid);