CREATE TABLE public.xlg_logging (
    lg_lgid integer NOT NULL,
    lg_severity character(1),
    lg_level integer NOT NULL DEFAULT 1,
    lg_isupdate boolean NOT NULL DEFAULT false,
    lg_caller character varying DEFAULT ''::character varying,
    lg_functionname character varying NOT NULL,
    lg_table character varying DEFAULT ''::character varying,
    lg_msg character varying NOT NULL,
    lg_datetime timestamp with time zone NOT NULL
);

ALTER TABLE public.xlg_logging ALTER COLUMN lg_lgid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.xlg_logging_lg_lgid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.xlg_logging
    ADD CONSTRAINT xlg_logging_pkey PRIMARY KEY (lg_lgid);