-- Tables owned by nextjs-shared. Run this in every consuming project's database.

CREATE TABLE IF NOT EXISTS public.xlg_logging
(
    lg_lgid       integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    lg_severity   character(1) COLLATE pg_catalog."default",
    lg_caller     character varying COLLATE pg_catalog."default" DEFAULT ''::character varying,
    lg_functionname character varying COLLATE pg_catalog."default" NOT NULL,
    lg_msg        character varying COLLATE pg_catalog."default" NOT NULL,
    lg_datetime   timestamp with time zone NOT NULL,
    CONSTRAINT xlg_logging_pkey PRIMARY KEY (lg_lgid)
);
